Ecommerce/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('category/', include('category.urls')),
    path('', include('product.urls')),
    path('order/', include('order.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns_api = [
    path('api/v1/', include('category.api.urls')),
    path('api/v1/', include('product.api.urls')),
    path('api/v1/', include('order.api.urls')),
    path('api/v1/', include('account.api.urls'))
]

urlpatterns += urlpatterns_api

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/urls.py
from django.urls import path
from .views import (
    remove_from_cart,
    reduce_quantity_item,
    add_to_cart,
    order_summary,
    increase_quantity_item,
    checkout,
)

app_name = 'order'

urlpatterns = [
    path('order-summary', order_summary, name='order_summary'),
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce-quantity-item'),
    path('increase-quantity-item/<pk>/', increase_quantity_item, name='increase-quantity-item'),
    path('checkout/', checkout, name='checkout')
]

product/api/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
]

product/urls.py
from django.urls import path

from .views import HomeView, ProductListView

app_name = 'product'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('products/', ProductListView.as_view(), name='product_list'),
]

product/models.py
from django.db import models

from base.models import TimeStampedModel
from category.models import Category
from account.models import User
from product.managers import ProductManager


class Color(TimeStampedModel):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class Size(TimeStampedModel):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class Product(TimeStampedModel):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='seller')
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='products')
    color = models.ForeignKey(Color, on_delete=models.PROTECT, null=True, blank=True)
    size = models.ForeignKey(Size, on_delete=models.PROTECT, null=True, blank=True)

    custom = ProductManager()
    objects = models.Manager()

    def __str__(self):
        return self.title


class Images(TimeStampedModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product/images')

    def __str__(self):
        return self.product.title

product/api/views.py
from django.core.cache import cache
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page

from rest_framework import generics
from django_filters import rest_framework as filters

from ..models import Product
from .serializers import ProductSerializer


@method_decorator(cache_page(60 * 5), name='dispatch')
class ProductListView(generics.ListAPIView):
    serializer_class = ProductSerializer
    filter_backends = [filters.DjangoFilterBackend]
    filterset_fields = ['color', 'size']

    def get_queryset(self):
        products = cache.get('products')
        if products is None:
            products = Product.objects.select_related('category').prefetch_related('color', 'size').all()
            cache.set('products', products)
        return products


class ProductDetailView(generics.RetrieveAPIView):
    serializer_class = ProductSerializer
    queryset = Product.objects.all()

product/views.py
from django.views.generic import ListView

from .models import Product


class HomeView(ListView):
    model = Product
    template_name = 'home.html'
    context_object_name = 'products'


class ProductListView(ListView):
    model = Product
    template_name = 'product/product_list.html'
    context_object_name = 'products'

templates/product/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Product list {% endblock %}

{% block content %}

    <!-- ========================= SECTION PAGETOP ========================= -->
    <section class="section-pagetop bg">
        <div class="container">
            <h2 class="title-page">Our Store</h2>

        </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION INTRO END// ========================= -->

    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
        <div class="container">

            <div class="row">
                <aside class="col-md-3">

                    <div class="card">
                        <article class="filter-group">
                            <header class="card-header">
                                <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true"
                                   class="">
                                    <i class="icon-control fa fa-chevron-down"></i>
                                    <h6 class="title">Categories</h6>
                                </a>
                            </header>
                            <div class="filter-content collapse show" id="collapse_1" style="">
                                <div class="card-body">

                                    <ul class="list-menu">
                                        {% for category in categories %}
                                            <li><a href="#">{{ category.name }} </a></li>
                                        {% endfor %}
                                    </ul>

                                </div> <!-- card-body.// -->
                            </div>
                        </article> <!-- filter-group  .// -->
                        <article class="filter-group">
                            <header class="card-header">
                                <a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true"
                                   class="">
                                    <i class="icon-control fa fa-chevron-down"></i>
                                    <h6 class="title">Sizes </h6>
                                </a>
                            </header>
                            <div class="filter-content collapse show" id="collapse_4" style="">
                                <div class="card-body">
                                    <label class="checkbox-btn">
                                        <input type="checkbox">
                                        <span class="btn btn-light"> XS </span>
                                    </label>

                                    <label class="checkbox-btn">
                                        <input type="checkbox">
                                        <span class="btn btn-light"> SM </span>
                                    </label>

                                    <label class="checkbox-btn">
                                        <input type="checkbox">
                                        <span class="btn btn-light"> LG </span>
                                    </label>

                                    <label class="checkbox-btn">
                                        <input type="checkbox">
                                        <span class="btn btn-light"> XXL </span>
                                    </label>
                                </div><!-- card-body.// -->
                            </div>
                        </article> <!-- filter-group .// -->

                        <article class="filter-group">
                            <header class="card-header">
                                <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true"
                                   class="">
                                    <i class="icon-control fa fa-chevron-down"></i>
                                    <h6 class="title">Price range </h6>
                                </a>
                            </header>
                            <div class="filter-content collapse show" id="collapse_3" style="">
                                <div class="card-body">

                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label>Min</label>
                                            <!-- <input class="form-control" placeholder="$0" type="number"> -->
                                            <select class="mr-2 form-control">
                                                <option value="0">$0</option>
                                                <option value="50">$50</option>
                                                <option value="100">$100</option>
                                                <option value="150">$150</option>
                                                <option value="200">$200</option>
                                                <option value="500">$500</option>
                                                <option value="1000">$1000</option>
                                            </select>
                                        </div>
                                        <div class="form-group text-right col-md-6">
                                            <label>Max</label>
                                            <select class="mr-2 form-control">
                                                <option value="50">$50</option>
                                                <option value="100">$100</option>
                                                <option value="150">$150</option>
                                                <option value="200">$200</option>
                                                <option value="500">$500</option>
                                                <option value="1000">$1000</option>
                                                <option value="2000">$2000+</option>
                                            </select>
                                        </div>
                                    </div> <!-- form-row.// -->
                                    <button class="btn btn-block btn-primary">Apply</button>
                                </div><!-- card-body.// -->
                            </div>
                        </article> <!-- filter-group .// -->

                    </div> <!-- card.// -->

                </aside> <!-- col.// -->
                <main class="col-md-9">

                    <header class="border-bottom mb-4 pb-3">
                        <div class="form-inline">
                            <span class="mr-md-auto">32 Items found </span>

                        </div>
                    </header><!-- sect-heading -->

                    <div class="row">
                        {% for product in products %}
                            {% if product.quantity > 0 %}
                                <div class="col-md-4">
                                    <figure class="card card-product-grid">
                                        <div class="img-wrap">

                                            <img src="images/items/1.jpg">

                                        </div> <!-- img-wrap.// -->
                                        <figcaption class="info-wrap">
                                            <div class="fix-height">
                                                <a class="title">{{ product.title }}</a>
                                                <div class="price-wrap mt-2">
                                                    <span class="price">${{ product.price }}</span>
                                                </div>
                                            </div>
                                            {% if user.is_authenticated %}
                                                <a href="{% url 'order:add-to-cart' product.pk %}"
                                                   class="btn btn-block btn-primary">Savatga qo'shish </a>
                                            {% else %}
                                                <a href="{% url 'login' %}"
                                                   class="btn btn-block btn-primary">Savatga qo'shish </a>
                                            {% endif %}
                                        </figcaption>
                                    </figure>
                                </div> <!-- col.// -->
                            {% endif %}
                        {% endfor %}
                    </div> <!-- row end.// -->


                    <nav class="mt-4" aria-label="Page navigation sample">
                        <ul class="pagination">
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link" href="#">Next</a></li>
                        </ul>
                    </nav>

                </main> <!-- col.// -->

            </div>

        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock %}