Ecommerce/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('category/', include('category.urls')),
    path('', include('product.urls')),
    path('order/', include('order.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns_api = [
    path('api/v1/', include('category.api.urls')),
    path('api/v1/', include('product.api.urls')),
    path('api/v1/', include('order.api.urls')),
    path('api/v1/', include('account.api.urls'))
]

urlpatterns += urlpatterns_api

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/urls.py
from django.urls import path
from .views import (
    remove_from_cart,
    reduce_quantity_item,
    add_to_cart,
    order_summary,
    increase_quantity_item,
    checkout,
)

app_name = 'order'

urlpatterns = [
    path('order-summary', order_summary, name='order_summary'),
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce-quantity-item'),
    path('increase-quantity-item/<pk>/', increase_quantity_item, name='increase-quantity-item'),
    path('checkout/', checkout, name='checkout')
]

product/urls.py
from django.urls import path

from .views import HomeView, ProductListView

app_name = 'product'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('products/', ProductListView.as_view(), name='product_list'),
]

base/models.py
from django.db import models

class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

base/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache"/>
    <meta http-equiv="cache-control" content="max-age=604800"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %} {% endblock %}</title>

    <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Font awesome 5 -->
    <link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)"/>

    <!-- custom javascript -->
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>

    <script type="text/javascript">
        /// some script

        // jquery ready start
        $(document).ready(function () {
            // jQuery code

        });
        // jquery end
    </script>

</head>
<body>


{% include 'header.html' %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

{% block content %}
    
{% endblock %}

<footer class="section-footer border-top">
    <div class="container">
        <section class="footer-bottom border-top row">
            <div class="col-md-3">
                <p class="text-left"> &copy 2024 Jasurbek Saydullayev </p>
            </div>
            <div class="col-md-8 text-md-right">
                <span class="px-2">jasurbek.saydullayev@list.ru</span>
                <span class="px-2">+998-99-575-81-56</span>
                <span class="px-2">Toshkent shahri, Yunusobod tuman, Amir Temur 5A</span>
            </div>
        </section>
    </div>
</footer>
</body>
</html>

templates/header.html
{% load static %}
<header class="section-header">


    <section class="header-main border-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-2 col-md-3 col-6">
                    <a href="{% url 'product:home' %}" class="brand-wrap">
                        <img class="logo" src="{% static 'images/logo.png' %}">
                    </a> <!-- brand-wrap.// -->
                </div>
                <div class="col-lg col-sm col-md col-6 flex-grow-0">
                    <div class="category-wrap dropdown d-inline-block float-right">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bars"></i> All category
                        </button>
                        <div class="dropdown-menu">
                            {% for category in categories %}
                                <a class="dropdown-item" href="#">{{ category.name }} </a>
                            {% endfor %}
                        </div>
                    </div>  <!-- category-wrap.// -->
                </div> <!-- col.// -->
                <a href="{% url 'product:product_list' %}" class="btn btn-outline-primary">Store</a>
                <div class="col-lg  col-md-6 col-sm-12 col">
                    <form action="#" class="search">
                        <div class="input-group w-100">
                            <input type="text" class="form-control" style="width:60%;" placeholder="Search">

                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form> <!-- search-wrap .end// -->
                </div> <!-- col.// -->
                <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        <div class="widget-header">
                            {% if user.is_authenticated %}
                                <a href="{% url 'user-detail' %}"> {{ user.username }} </a>
                                <a href="{% url 'logout' %}"> | Logout </a>
                            {% else %}
                                <div>
                                    <a class="btn btn-primary-light" href="{% url 'login' %}">Kirish</a>
                                </div>
                            {% endif %}
                        </div>
                        {% if user.is_authenticated %}
                            <a href="{% url 'order:order_summary' %}" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">{{ order_count }}</span>
                        {% else %}
                            <a href="{% url 'login' %}" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">{{ order_count }}</span>
                        {% endif %}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>

</header> 

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}

<!-- ========================= SECTION MAIN ========================= -->
<section class="section-intro padding-y-sm">
<div class="container">

<div class="intro-banner-wrap">
	<img src="{% static 'images/banners/1.jpg' %}" class="img-fluid rounded">
</div>

</div> <!-- container //  -->
</section>
<!-- ========================= SECTION MAIN END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y-sm">
<div class="container">

<header class="section-heading">
	<a href="{% url 'product:product_list' %}" class="btn btn-outline-primary float-right">See all</a>
	<h3 class="section-title">Popular products</h3>
</header><!-- sect-heading -->


<div class="row">
    {% for product in products %}
	<div class="col-md-3">
		<div class="card card-product-grid">
			<a href="./product-detail.html" class="img-wrap"> <img src="{% static 'images/items/1.jpg' %}"> </a>
			<figcaption class="info-wrap">
				<a href="./product-detail.html" class="title">{{ product.name }}</a>
				<div class="price mt-1">${{ product.name }}</div> <!-- price-wrap.// -->
				<div class="price mt-1">${{ product.price }}</div> <!-- price-wrap.// -->
			</figcaption>
		</div>
	</div> <!-- col.// -->
    {% endfor %}

</div> <!-- row.// -->

</div><!-- container // -->
</section>
<!-- ========================= SECTION  END// ========================= -->

{% endblock %}