Ecommerce/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('category/', include('category.urls')),
    path('', include('product.urls')),
    path('order/', include('order.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns_api = [
    path('api/v1/', include('category.api.urls')),
    path('api/v1/', include('product.api.urls')),
    path('api/v1/', include('order.api.urls')),
    path('api/v1/', include('account.api.urls'))
]

urlpatterns += urlpatterns_api

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/api/urls.py
from django.urls import path

from .views import OrderList, AddOrderView, RemoveOrderView, InkrementOrderItemView, DekrementOrderItemView

urlpatterns = [
    path('orders/', OrderList.as_view(), name='order_list'),
    path('orders/<int:pk>/', AddOrderView.as_view(), name='add_order'),
    path('orders/remove/<int:pk>/', RemoveOrderView.as_view(), name='remove_orderitem'),
    path('orders/inkrement/<int:pk>/', InkrementOrderItemView.as_view(), name='inkrement_orderitem'),
    path("orders/dekrement/<int:pk>/", DekrementOrderItemView.as_view(), name='dekrement_orderitem')
]

order/urls.py
from django.urls import path
from .views import (
    remove_from_cart,
    reduce_quantity_item,
    add_to_cart,
    order_summary,
    increase_quantity_item,
    checkout,
)

app_name = 'order'

urlpatterns = [
    path('order-summary', order_summary, name='order_summary'),
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce-quantity-item'),
    path('increase-quantity-item/<pk>/', increase_quantity_item, name='increase-quantity-item'),
    path('checkout/', checkout, name='checkout')
]

product/urls.py
from django.urls import path

from .views import HomeView, ProductListView

app_name = 'product'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('products/', ProductListView.as_view(), name='product_list'),
]

order/models.py
from django.db import models

from base.models import TimeStampedModel
from account.models import User
from product.models import Product


class OrderItem(TimeStampedModel):
    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orderitem')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='orderitem')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.quantity} * {self.product.price} = {self.total_price}'

    def calc_price(self):
       return self.quantity * self.product.price

    def save(self, *args, **kwargs):
        self.total_price = self.calc_price()
        return super(OrderItem, self).save(*args, **kwargs)


class Order(TimeStampedModel):
    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='order')
    orderitem = models.ManyToManyField(OrderItem)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.total_price}'

    def calc_total(self):
        total = 0
        for orderitem in self.orderitem.objects.all():
            total += orderitem.total_price
        return total

    # def save(self, *args, **kwargs):
    #     self.total_price = self.calc_total()
    #     return super(Order, self).save(*args, **kwargs)

order/api/views.py
from django.shortcuts import get_object_or_404
from django.core.cache import cache
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import permissions
from order.api.permissions import OrderPermission, OrderItemAuthorPermission
from order.api.serializers import OrderSerializer
from order.models import Order, OrderItem
from product.models import Product


@method_decorator(cache_page(60 * 5), name='dispatch')
class OrderList(generics.ListAPIView):
    serializer_class = OrderSerializer

    def get_queryset(self):
        orderitem = cache.get('orderitem')
        if orderitem is None:
            orderitem = Order.objects.prefetch_related('orderitem').all()
            cache.set('orderitem', orderitem)
        return orderitem


class AddOrderView(APIView):
    permission_classes = [permissions.IsAuthenticated, OrderPermission]

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        self.check_object_permissions(self.request, product)
        order, created = Order.objects.get_or_create(customer=request.user, ordered=False)
        orderitem, item_created = OrderItem.objects.get_or_create(product=product, customer=request.user, ordered=False)
        if not item_created:
            orderitem.quantity += 1
            product.quantity -= 1
            orderitem.save()
        else:
            order.orderitem.add(orderitem)
            product.quantity -= 1
            product.save()
        return Response({"message": "Ok"}, status=status.HTTP_201_CREATED)


class RemoveOrderView(APIView):
    permission_classes = [permissions.IsAuthenticated, OrderItemAuthorPermission]

    def post(self, request, pk):
        orderitem = get_object_or_404(OrderItem, pk=pk)
        order = Order.objects.filter(orderitem=orderitem).first()
        self.check_object_permissions(self.request, orderitem)
        orderitem.product.quantity += orderitem.quantity
        order.orderitem.remove(orderitem)
        orderitem.delete()
        return Response({"message": "Ok"}, status=status.HTTP_202_ACCEPTED)


class InkrementOrderItemView(APIView):
    permission_classes = [permissions.IsAuthenticated, OrderItemAuthorPermission]

    def post(self, request, pk):
        orderitem = get_object_or_404(OrderItem, pk=pk)
        self.check_object_permissions(self.request, orderitem)
        if not orderitem:
            return Response({"error": "OrderItem not found"}, status=status.HTTP_404_NOT_FOUND)
        else:
            orderitem.quantity += 1
            orderitem.product.quantity -= 1
            orderitem.save()
            orderitem.product.save()
        return Response({"message": "Ok"}, status=status.HTTP_200_OK)


class DekrementOrderItemView(APIView):
    permission_classes = [permissions.IsAuthenticated, OrderItemAuthorPermission]

    def post(self, request, pk):
        orderitem = get_object_or_404(OrderItem, pk=pk)
        order = Order.objects.filter(orderitem=orderitem).first()
        self.check_object_permissions(self.request, orderitem)
        if orderitem.quantity == 1:
            orderitem.product.quantity += 1
            order.orderitem.remove(orderitem)
            orderitem.delete()
        else:
            orderitem.quantity -= 1
            print(orderitem.product.quantity)
            orderitem.product.quantity += 1
            print(orderitem.product.quantity)
            orderitem.save()
        orderitem.product.save()
        return Response({"message": "Ok"}, status=status.HTTP_200_OK)

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.db.models import Sum
from django.shortcuts import render, get_object_or_404, redirect

from .models import (
    Order,
    OrderItem
)

from product.models import Product
from .tasks import send_email


@login_required(login_url='/accounts/login/')
def order_summary(request):
    order = Order.objects.filter(customer=request.user, ordered=False).annotate(
        order_total_price=Sum('orderitem__total_price'),
    ).first()
    if order is not None:
        if order.order_total_price is None:
            order.order_total_price = 0
            context = {'order': 0.00, 'discount': 0.00, 'total': 0.00}
        else:
            discount = round(float(order.order_total_price) * 0.01, 3)
            total = float(order.order_total_price) - discount
            context = {
                'order': order,
                'discount': discount,
                'total': total,
            }
    else:
        context = {'order': 0.00, 'discount': 0.00, 'total': 0.00}
    return render(request, 'order/cart.html', context)


@login_required()
def checkout(request):
    order = Order.objects.filter(customer=request.user, ordered=False).annotate(
        order_total_price=Sum('orderitem__total_price'),
    ).first()

    if order is None:
        return render(request, 'order/checkout.html', context={"message": "Sizda sotib olingan buyumlar yo'q"})
    discount = round(float(order.order_total_price) * 0.01, 3)
    total = float(order.order_total_price) - discount
    message = ""
    orderitems = OrderItem.objects.filter(customer=request.user, ordered=False)
    for orderitem in orderitems:
        message += (f"Mahsulot nomi: {orderitem.product.title}\n"
                    f"Mahsulot soni: {orderitem.quantity}\n"
                    f"Mahsulot rangi: {orderitem.product.color}\n"
                    f"Mahsulot o'lchami: {orderitem.product.size}\n"
                    f"Bitta Mahsulotning narxi: ${orderitem.product.price}\n\n\n")
    message += f"Mahsulotlarning umumiy narxi: ${order.order_total_price}\n\n"
    message += f"Siz uchun chegirma: ${float(discount)}\n\n"
    message += f"To'lashingiz kerak bo'lgan narx: ${total}\n\n"
    send_email.delay(order.id, message)
    return render(request, 'order/checkout.html')


@login_required
def add_to_cart(request, pk):
    product = get_object_or_404(Product, pk=pk)
    order_item, created = OrderItem.objects.get_or_create(
        product=product,
        customer=request.user,
    )

    order_qs = Order.objects.filter(customer=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.orderitem.filter(product__pk=product.pk).exists():
            messages.info(request, "Mahsulot oldin savatingizga qo'shilgan")
            return redirect("product:product_list")
        else:
            order.orderitem.add(order_item)
            messages.info(request, "Mahsulot savatingizga qo'shildi")
            return redirect("product:product_list")
    else:
        order = Order.objects.create(customer=request.user)
        # send_email.delay(order.id, product)
        order.orderitem.add(order_item)
        messages.info(request, "Mahsulot savatingizga qo'shildi")
        return redirect("order:order_summary")


# def buy(request)


@login_required
def remove_from_cart(request, pk):
    order_item = OrderItem.objects.get(pk=pk)
    order = order_item.order_set.all().first()
    if order:
        order.orderitem.remove(order_item)
        order_item.delete()
    return redirect("order:order_summary")


@login_required
def reduce_quantity_item(request, pk):
    product = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(
        customer=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitem.filter(product__pk=product.pk).exists():
            order_item = OrderItem.objects.filter(
                product=product,
                customer=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.product.quantity += 1
                order_item.product.save()
                order_item.save()
                messages.info(request, "Mahsulotingiz soni 1 taga kamaytirildi")
            else:
                order_item.delete()
                messages.info(request, "Mahsulot savatingizdan o'chirldi")
            return redirect("order:order_summary")
        else:
            messages.info(request, "Sizning savatingizda ushbu mahsulot mavjud emas")
            return redirect("order:order_summary")
    else:
        # add message doesnt have order
        messages.info(request, "You do not have an Order")
        return redirect("order:order_summary")


@login_required
def increase_quantity_item(request, pk):
    product = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(
        customer=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitem.filter(product__pk=product.pk).exists():
            order_item = OrderItem.objects.filter(
                product=product,
                customer=request.user,
                ordered=False
            )[0]
            if order_item.quantity < 10 and order_item.product.quantity >= 1:
                order_item.quantity += 1
                order_item.product.quantity -= 1
                order_item.product.save()
                order_item.save()
            elif order_item.product.quantity == 0:
                messages.info(request, "Bu Tovardan boshqa qolmagan")
                return redirect("order:order_summary")
            else:
                messages.info(request, "10 tadan ko'p olish mumkin emas")
                return redirect("order:order_summary")
            messages.info(request, "Mahsulot soni 1 taga ko'paytirildi")
            return redirect("order:order_summary")
        else:
            messages.info(request, "Bu mahsulot sizni savatingizda mavjud emas")
            return redirect("order:order_summary")
    else:
        messages.info(request, "Savatingiz bo'sh")
        return redirect("order:order_summary")

templates/order/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Cart {% endblock %}

{% block content %}
    <section class="section-content padding-y bg">
        <div class="container">

            <!-- ============================ COMPONENT 1 ================================= -->

            <div class="row">
                <aside class="col-lg-9">
                    <div class="card">
                        <table class="table table-borderless table-shopping-cart">
                            <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for orderitem in order.orderitem.all %}
                                <tr>
                                    <td>
                                        <figure class="itemside align-items-center">
                                            <div class="aside"><img src="" class="img-sm"></div>
                                            <figcaption class="info">
                                                <a class="title text-dark">{{ orderitem.product.title }}</a>
                                                <p class="text-muted small">{{ orderitem.product.description }}</p>
                                            </figcaption>
                                        </figure>
                                    </td>
                                    <td>
                                        <!-- col.// -->
                                        <div class="col">
                                            <div class="input-group input-spinner">
                                                <div class="input-group-prepend">
                                                    <a href="{% url 'order:reduce-quantity-item' orderitem.product.pk %}"
                                                       class="btn btn-light" type="button" id="button-plus"><i
                                                            class="fa fa-minus"></i></a>
                                                </div>
                                                <input type="text" class="form-control"
                                                       value="{{ orderitem.quantity }}">
                                                <div class="input-group-append">
                                                    <a href="{% url 'order:increase-quantity-item' orderitem.product.pk %}"
                                                       class="btn btn-light" type="button" id="button-minus"><i
                                                            class="fa fa-plus"></i></a>
                                                </div>
                                            </div> <!-- input-group.// -->
                                        </div> <!-- col.// -->
                                    </td>
                                    <td>
                                        <div class="price-wrap">
                                            <var class="price">${{ orderitem.total_price }}</var>
                                            <small class="text-muted"> ${{ orderitem.product.price }} each </small>
                                        </div> <!-- price-wrap .// -->
                                    </td>
                                    <td class="text-right">
                                        <a href="{% url 'order:remove-from-cart' orderitem.pk %}"
                                           class="btn btn-danger"> Remove</a>
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div> <!-- card.// -->

                </aside> <!-- col.// -->
                <aside class="col-lg-3">

                    <div class="card">
                        <div class="card-body">
                            <dl class="dlist-align">
                                <dt>Total price:</dt>
                                {% if not order.order_total_price %}
                                    <dd class="text-right">$ 0</dd>
                                {% else %}
                                    <dd class="text-right">${{ order.order_total_price }}.00</dd>
                                {% endif %}
                            </dl>
                            <dl class="dlist-align">
                                <dt>Discount:</dt>
                                <dd class="text-right"> ${{ discount }}</dd>
                            </dl>
                            <dl class="dlist-align">
                                <dt>Total:</dt>
                                {% if total %}
                                    <dd class="text-right text-dark b"><strong>${{ total }}</strong></dd>
                                {% else %}
                                    <dd class="text-right text-dark b"><strong>$0</strong></dd>
                                {% endif %}
                            </dl>
                            <hr>
                            <p class="text-center mb-3">
                                <img src="{% static '/images/misc/payments.png' %}" height="26">
                            </p>
                            <a href="{% url 'order:checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
                            <a href="{% url 'product:product_list' %}" class="btn btn-light btn-block">Continue Shopping</a>
                        </div> <!-- card-body.// -->
                    </div> <!-- card.// -->

                </aside> <!-- col.// -->


            </div> <!-- row.// -->
            <!-- ============================ COMPONENT 1 END .// ================================= -->

        </div> <!-- container .//  -->
    </section>

{% endblock %}

templates/order/checkout.html
{% extends 'base.html' %}

{% block title %} Checkout {% endblock %}

{% block content %}
    <br/><br/>
    <br/><br/>

    {% if message %}
        <h1 class="text-center">{{ message }}</h1>
    {% else %}
        <h3 class="text-center">Sotib olgan buyumlaringiz haqidagi ma'lumotlar emailingizga yuborildi <a
                href="{% url 'product:product_list' %}" class="btn btn-secondary text-center">Bosh sahifaga qaytish</a>
        </h3>
    {% endif %}

    
    <br/><br/>
    <br/><br/>
    <br/><br/>
    <br/><br/>
    <br/><br/>
    <br/><br/>
    <br/><br/>
    <br/><br/>
    <br/><br/>
    <br/><br/>

{% endblock %}